site_name: Jarvis-HEP Documentation
site_url: https://pengxuan-zhu-phys.github.io/Jarvis-Docs/

theme:
  name: material
  logo: assets/JarvisHEP.png
  favicon: assets/JarvisHEP.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
extra_css:
  - stylesheets/extra.gm95.css

plugins:
  - search
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
validation:
  nav:
    omitted_files: ignore

nav:
  - Home: index.md
  - Quick Start:
      - Installation: tutorial/Installation.md
      - First Scan (EggBox): tutorial/Common_workflow.md
      - Command Line Tools: tutorial/cli.md
      - First Module (EggBox): tutorial/eggbox.md
  - Jarvis-HEP Summary:
      - Task YAML Structure: core/yaml_overview.md
      - Sampler Summary: core/samplers.md
  - Jarvis-PLOT Summary:
      - Overview: jarvisplot/jarvisplot.md
  - Jarvis-Operas Summary:
      - Overview: package/jarvis-operas.md
