site_name: Jarvis-HEP Documentation
site_url: https://pengxuan-zhu-phys.github.io/Jarvis-Docs/

theme:
  name: material
  logo: assets/JarvisHEP.png
  favicon: assets/JarvisHEP.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
extra_css:
  - stylesheets/extra.gm95.css

plugins:
  - search

validation:
  nav:
    omitted_files: ignore

nav:
  - Home: index.md
  - Quick Start:
      - Installation: tutorial/Installation.md
      - First Scan (EggBox): tutorial/Common_workflow.md
      - Command Line Tools: tutorial/cli.md
  - Write A Scan:
      - Task YAML Structure: core/summary.md
      - YAML Overview: core/yaml_overview.md
      - Samplers Overview: core/samplers.md
      - Sampler Details: samplers/index.md
      - Calculators: core/calculator.md
      - Operas: core/operas.md
      - EnvReqs: core/environment.md
      - Libraries: core/library.md
      - Symbolic Expressions: core/symbol.md
      - Utils: core/utils.md
      - IO File Types: core/io_summary.md
  - Jarvis-PLOT: jarvisplot/jarvisplot.md
  - Jarvis-Operas: package/jarvis-operas.md
